### ISSUE TITLE
problems when communicating with real Linux socket

### ISSUE THREAD

**Issue by huangrt01** [gcidart/cs144#1]
Hello, I read your implementations yesterday and found your project has concise modularity and elegant coding style.

In lab 4, I failed 5~10 tests when communicating with the real Linux sockets, starting from Test #147. Can you have any suggestions on how to debug or solve such problems? Thanks.

One of the test shell scripts that I always fail is ../txrx.sh -isDnd 128K -w 8K -l 0.1.
Here are two types of typical errors:

        Start 155: t_icnD_128K_8K_lL
150/159 Test #155: t_icnD_128K_8K_lL ................***Failed    2.12 sec
./apps/tcp_ipv4 -t 12 -w 8192 -Lu 0.1 -Ld 0.1 -d tun144 -a 169.254.144.9 169.254.144.1 19160 >/tmp/tmp.9Qc3I7xmcF </tmp/tmp.AvMPx99fBg
DEBUG: Connecting to 169.254.144.1:19160... done.
DEBUG: Outbound stream to 169.254.144.1:19160 finished (65340 bytes still in flight).
DEBUG: Outbound stream to 169.254.144.1:19160 has been fully acknowledged.
DEBUG: Inbound stream from 169.254.144.1:19160 finished cleanly.
DEBUG: Waiting for lingering segments (e.g. retransmissions of FIN) from peer...
DEBUG: Waiting for clean shutdown... DEBUG: TCP connection finished cleanly.
done.
ERROR: 823016bab1e111fbeabf062fcb389ce024a42b2bb13803230efe6319dea7e4f6 neq 823016bab1e111fbeabf062fcb389ce024a42b2bb13803230efe6319dea7e4f6 or 2ac59e7dd0c37923595ee5ed98e08e2716ae8f48d471acd90bdef7505e67d37d

        Start 164: t_isnD_128K_8K_lL
159/159 Test #164: t_isnD_128K_8K_lL ................***Failed    6.59 sec
DEBUG: Listening for incoming connection... ./apps/tcp_native 169.254.144.9 3837 >/tmp/tmp.5jXWFyiYCO </tmp/tmp.w7NZz41vnt
new connection from 169.254.144.1:37144.
DEBUG: Outbound stream to 169.254.144.1:37144 finished (60984 bytes still in flight).
DEBUG: Inbound stream from 169.254.144.1:37144 finished cleanly.
DEBUG: Waiting for clean shutdown... DEBUG: TCP connection finished uncleanlyException: EventLoop: error on polled file descriptor
done.
Error in _rt_connect

Here is my benchmark result.

 $ ./apps/tcp_benchmark
CPU-limited throughput                : 0.86 Gbit/s
CPU-limited throughput with reordering: 0.44 Gbit/s

I also found that my implementation is weak in dealing with reordering input, maybe this is the bottleneck.

(Environment: provided VirtualBox Image; MacOS Catalina)

**Comment by gcidart** [comment]
Hi,

I had struggled a lot to pass lab4.
If you see commit 4af91bafabea0af7065859b51a7c07b404d8198b, i had to fix issues in code for the previous labs.

What helped me to debug was to print header and length_in_sequence_space for every incoming and outgoing TCP segment. 
In your log for TC#150, there is a hash error mismatch. Initially i was under the impression that data was getting corrupted when i was getting hash error mismatch. But on opening the tmp file, i realised that the file size was not equal to the expected 128K. The file size matched the difference of sequence numbers  of last and first TCP segments sent or received. 
Most of the bugs were coming to front when uplink and/or downlink loss rate parameter of txrx.sh was not zero.
For example - The final bug which i had resolved was tcp_sender generating a segment even when payload size was zero. This segment was copied to retransmission_queue. Only in the case of a non-zero loss rate parameter, this empty segment was causing all sorts of problems.

I don't think i had seen "EventLoop: error on polled file descriptor"

**Comment by huangrt01** [comment]
Thank you for your detailed and useful advice!!!   
I would try it later on.

**Comment by huangrt01** [comment]
Thanks! I passed all the tests after studying your code. Although I spend a lot of time modifying my TCPConnection and TCPSender, there is only one furtive and deadly bug in my TCPReceiver :(........        
The bug corresponds to this line of your code:
`(index_start >= seqno_start && index_start <= seqno_end )  || (payload_end >= seqno_start && index_end <=seqno_end) `
The variable "payload_end" is really important, without which there are no ways for me to pass all the tests. How could you find out this detail !!!
